# Generated by Django 5.1.4 on 2025-01-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('node_type', models.CharField(default='round', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='knowledge_web.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('connection_type', models.CharField(default='line', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='knowledge_web.graph')),
                ('ending_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='knowledge_web.node')),
                ('starting_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='knowledge_web.node')),
            ],
        ),
    ]
